---
title: "Helpers"
permalink: /docs/dev/helpers/
last_modified_at: 2026-03-20
toc: true
toc_sticky: true
sidebar:
  nav: docs-dev
---

* Gallery

Here are the steps to make the changes:

1. Copy the default gallery layout from the Minimal Mistakes gem (e.g.
   =~/.gem/ruby/3.1.3/gems/minimal-mistakes-jekyll-4.26.0/_includes/gallery=) into
   your local =_includes= directory.

2. Apply these changes:

   {% raw %}
   #+begin_src diff
   diff -u minimal-mistakes/_includes/gallery josephs-blog/_includes/gallery
   --- minimal-mistakes/_includes/gallery	2023-12-15 19:03:51
   +++ josephs-blog/_includes/gallery	2026-03-01 23:18:56
   @@ -6,6 +6,8 @@

    {% if include.layout %}
      {% assign gallery_layout = include.layout %}
   +{% elsif include.columns %}
   +  {% assign gallery_layout = "custom-grid" %}
    {% else %}
      {% if gallery.size == 2 %}
        {% assign gallery_layout = 'half' %}
   @@ -16,6 +18,48 @@
      {% endif %}
    {% endif %}

   +{% if include.columns %}
   +
   +<figure class="{{ gallery_layout }} {{ include.class }}"
   +        style="grid-template-columns: repeat({{ include.columns }}, 1fr);">
   +  {% for img in gallery %}
   +    <figure>
   +      <a {% if img.url %}
   +           href="{{ img.url | relative_url }}"
   +         {% elsif img.image_path %}
   +           href="{{ img.image_path | relative_url }}"
   +         {% else %}
   +           href="{{ img | relative_url }}"
   +         {% endif %}
   +
   +         {% if img.title %}
   +         {% comment %} Parse Liquid syntax in titles {% endcomment %}
   +           title="{{ img.title | liquify | markdownify | remove: '<p>' |
   +                     remove: '</p>' | strip | newline_to_br | split: '<br />' |
   +                     join: '</p><p>' | prepend: '<p>' | append: '</p>' |
   +                     escape }}"
   +         {% elsif img.alt %}
   +           title="{{ img.alt }}"
   +         {% endif %}>
   +
   +        <img {% if img.image_path %}
   +               src="{{ img.image_path | relative_url }}"
   +             {% else %}
   +               src="{{ img | relative_url }}"
   +             {% endif %}
   +
   +             alt="{% if img.alt %}{{ img.alt }}{% endif %}">
   +      </a>
   +    </figure>
   +  {% endfor %}
   +  {% if include.caption %}
   +    <figcaption>{{ include.caption | markdownify | remove: "<p>" | remove: "</p>" }}</figcaption>
   +  {% endif %}
   +</figure>
   +
   +{% else %}
   +
   +<!-- Preserve the original style -->
    <figure class="{{ gallery_layout }} {{ include.class }}">
      {% for img in gallery %}
        {% if img.url %}
   @@ -33,3 +77,5 @@
        <figcaption>{{ include.caption | markdownify | remove: "<p>" | remove: "</p>" }}</figcaption>
      {% endif %}
    </figure>
   +
   +{% endif %}
   #+end_src
   {% endraw %}

3. Add these styles in your =assets/css/main.scss=:

   #+begin_src css
   // Enable more columns in a gallery
   .page__content .custom-grid {
     display: grid;
     gap: 0.5em;
   }

   .custom-grid figure {
     margin: 0;
     width: 100%;
   }

   .custom-grid figcaption {
     grid-column: 1 / -1;
   }

   .custom-grid img {
     margin-bottom: 0;
   }
   #+end_src

4. Create a new plugin file =_plugins/liquify.rb= to add a filter that evaluates
   Liquid syntax inside front matter strings:

   #+begin_src ruby
   module Jekyll
     module LiquifyFilter
       def liquify(input)
         Liquid::Template.parse(input.to_s).render(@context)
       end
     end
   end
   Liquid::Template.register_filter(Jekyll::LiquifyFilter)
   #+end_src

* Link Abbreviations

Related articles:

- [Enabling Link Abbreviations in Minimal Mistakes]({{site.url}}/blog/web/link-abbr/)
- [Enabling Drafting in Org Mode in Minimal Mistakes](/blog/web/enable-org-mode/#configurations-links-link-abbreviations)
- [User Guide: Link Abbreviations]({{ site.baseurl }}/docs/helpers/#link-abbreviations)

* Loading Local Files

Related articles:

- [Loading Local Images in Minimal Mistakes]({{site.url}}/blog/web/local-images/)

* Furigana
** Automatic Furigana Parsing
*** Requirements

I found an awesome browser extension called [[https://chromewebstore.google.com/detail/furiganator/ijfcmmkkmogaclaafpgcjdfcfibmhcfa][Furiganator]] which can insert
Furigana (Ruby text) in the webpage with the following features:

- Very fast and reliable.
- Furigana in Hiragana, Katakana or Romaji.
- Option to show Furigana only on mouse over.
- Option to make the furigana text unselectable.
- Option to use color-tags to easily identify the kanji level or grade.
- Multiple color themes.

In its Licenses, Certificates and Acknowledgements it describes the technologies
used:

- Icons8 - Icons provided by https://icons8.com
- Kanji API and its dependencies - This Extension uses parts of [[https://github.com/onlyskin/kanjiapi.dev][Kanji API]] and by
  extension, EDICT and KANJIDICT from [[https://www.edrdg.org/][Electronic Dictionary Research and Development Group]].
- Kuromoji.JS and its dependencies - This Extension uses [[https://github.com/takuyaa/kuromoji.js][Kuromoji.JS]] as
  Morphological Analyzer.
- Kuroshiro and its dependencies - This Extension uses [[https://github.com/hexenq/kuroshiro][Kuroshiro]] for its core
  functionality, and by extension the [[https://github.com/hexenq/kuroshiro-analyzer-kuromoji][Kuroshiro-analyzer-kuromoji]]
- Webpack and its dependencies - This Extensions uses [[https://webpack.js.org/][Webpack]]

Now I want to implement the same features in our minimal-mistakes-plus plugin
with the same technologies. Specifically,

- It should be very fast and reliable.
- Use the the option ~furigana: true/false~ in the front matter to turn the
  whole furigana parsing process on (~true~) or off (~false~ or unset).

- It can add Furigana in Hiragana, Katakana or Romaji automatically to normal
  texts without the furigana pattern using the same technologies as Furiganator
  depending on the option ~furigana_mode~, which

  - applies to the whole document when specified in the front matter:

    #+begin_src text
    furigana_mode: hiragana/katakana/romaji
    #+end_src

  - applies to only the paragraphs marked by the attribute syntax:

    #+begin_src text
    {: furigana_mode="hiragana/katakana/romaji"}
    #+end_src

  The attribute syntax takes precedence if both applies to a paragraph.

  If the option is unset, default to ~hiragana~.

- Use the option ~furigana_selectable: true/false~ in the front matter to make
  the furigana text selectable (~true~) or unselectable (~false~ or unset).

- Use the option ~furigana_mouse_over: true/false~ to only show Furigana on
  mouse over (~true~) or to show it all the time (~false~ or unset).

- Option to use color-tags to easily identify the kanji level or grade (Do not
  implement).
- Multiple color themes (Do not implement).

**** Kramdown attribute syntax

These options can be applied per paragraph with the Kramdown attribute syntax:

#+begin_src text
{: furigana_mode="hiragana/katakana/romaji" furigana_selectable="true/false" furigana_mouse_over="true/fasle"}
#+end_src

The attribute syntax overrides the same option in the front matter.

For the options ~furigana_selectable~ and ~furigana_mouse_over~:

- If specified in the front matter add a toolbar just above the table of contents (~class="toc"~) and inside the sidebar `class="sidebar__right sticky"`. Then add a small toggle icon (different looks for on and off) for each option inside the toolbar so that they can be toggled on or off for the whole page.

- If specified per paragraph in Kramdown attribute syntax, add the same toggle icon for each option just above the marked paragraph so that they can be toggled on or off only for that paragraph.

The HTML of the sidebar:

#+begin_src html
<aside class="sidebar__right sticky">
  <nav class="toc" aria-label="Table of contents">
    <header><h4 class="nav__title">
        <i class="fas fa-file-alt"></i> On this page</h4>
    </header>
  </nav>
</aside>
#+end_src

Use different icons for ~furigana_selectable~ and ~furigana_mouse_over~, and each icon should still have different looks when on and off. Make the ~frgntr-global-toolbar~ prettier and more nicely integrated with the theme.

Use the following layout for the toolbar above the TOC:

#+begin_src text
Tools        <-- Title of the entire toolbar section, background color same as the "nav__title" of the TOC
Furigana     <-- Title of the Furigana section, background color same as current
icon1 icon2  <-- The icons, smaller, more compact, no background color

# Light dim border between the sections.
#+end_src

**** Integration with Existing Furigana Parsing

For the existing furigana parsing process dealing with the pattern:

#+begin_src text
（X｜Y｜Z：X1｜Y1｜Z1）
#+end_src

its processing logic should be kept intact, with these additional changes:

- Now it belongs to the whole furigana parsing process which can be turned on or
  off using the option ~furigana: true/false~ as mentioned above.
- If it's turned off, convert all furigana patterns to normal texts without the
  pattern in the output, that is, ~（X｜Y｜Z：X1｜Y1｜Z1）~ becomes ~XYZ~.
- The pattern takes precedence over the automatic parsing, that is, a pattern
  should not be sent for automatic processing.

**** Example Outputs

Here is an example of how the Furiganator extension converts a piece of text to
HTML when "Make furigana unselectable" and "Only show furigana on mouse hover"
are turned on:

本日はお時間をいただき、ありがとうございます。私はマカオにあるマカオ理工大学を4
年制の学士課程で卒業しました。3ヶ月後、鶴ヶ崎さんと会う。

HTML Output:

#+begin_src html
<ruby furiganated="true">本日<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">ほんじつ</rt>
  <rp>)</rp>
</ruby>はお<ruby furiganated="true">時間<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">じかん</rt>
  <rp>)</rp>
</ruby>をいただき、ありがとうございます。<ruby furiganated="true">私<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">わたし</rt>
  <rp>)</rp>
</ruby>はマカオにあるマカオ<ruby furiganated="true">理工<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">りこう</rt>
  <rp>)</rp>
</ruby><ruby furiganated="true">大学<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">だいがく</rt>
  <rp>)</rp>
</ruby>を4 <ruby furiganated="true">年<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">とし</rt>
  <rp>)</rp>
</ruby><ruby furiganated="true">制<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">せい</rt>
  <rp>)</rp>
</ruby>の<ruby furiganated="true">学士<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">がくし</rt>
  <rp>)</rp>
</ruby><ruby furiganated="true">課程<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">かてい</rt>
  <rp>)</rp>
</ruby>で<ruby furiganated="true">卒業<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">そつぎょう</rt>
  <rp>)</rp>
</ruby>しました。3<ruby furiganated="true">ヶ月<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">かげつ</rt>
  <rp>)</rp>
</ruby><ruby furiganated="true">後<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">ご</rt>
  <rp>)</rp>
</ruby>、<ruby furiganated="true">鶴<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">つる</rt>
  <rp>)</rp>
</ruby>ヶ<ruby furiganated="true">崎<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">さき</rt>
  <rp>)</rp>
</ruby>さんと<ruby furiganated="true">会<rp>(</rp>
  <rt class="frgntr_hidden frgntr_unselectable ">あ</rt>
  <rp>)</rp>
</ruby>う。
#+end_src

When "Make furigana unselectable" and "Only show furigana on mouse hover" are
both turned off:

#+begin_src html
<ruby furiganated="true">本日<rp>(</rp>
  <rt class="">ほんじつ</rt>
  <rp>)</rp>
</ruby>はお<ruby furiganated="true">時間<rp>(</rp>
  <rt class="">じかん</rt>
  <rp>)</rp>
</ruby>をいただき、ありがとうございます。<ruby furiganated="true">私<rp>(</rp>
  <rt class="">わたし</rt>
  <rp>)</rp>
</ruby>はマカオにあるマカオ<ruby furiganated="true">理工<rp>(</rp>
  <rt class="">りこう</rt>
  <rp>)</rp>
</ruby><ruby furiganated="true">大学<rp>(</rp>
  <rt class="">だいがく</rt>
  <rp>)</rp>
</ruby>を4 <ruby furiganated="true">年<rp>(</rp>
  <rt class="">とし</rt>
  <rp>)</rp>
</ruby><ruby furiganated="true">制<rp>(</rp>
  <rt class="">せい</rt>
  <rp>)</rp>
</ruby>の<ruby furiganated="true">学士<rp>(</rp>
  <rt class="">がくし</rt>
  <rp>)</rp>
</ruby><ruby furiganated="true">課程<rp>(</rp>
  <rt class="">かてい</rt>
  <rp>)</rp>
</ruby>で<ruby furiganated="true">卒業<rp>(</rp>
  <rt class="">そつぎょう</rt>
  <rp>)</rp>
</ruby>しました。3<ruby furiganated="true">ヶ月<rp>(</rp>
  <rt class="">かげつ</rt>
  <rp>)</rp>
</ruby><ruby furiganated="true">後<rp>(</rp>
  <rt class="">ご</rt>
  <rp>)</rp>
</ruby>、<ruby furiganated="true">鶴<rp>(</rp>
  <rt class="">つる</rt>
  <rp>)</rp>
</ruby>ヶ<ruby furiganated="true">崎<rp>(</rp>
  <rt class="">さき</rt>
  <rp>)</rp>
</ruby>さんと<ruby furiganated="true">会<rp>(</rp>
  <rt class="">あ</rt>
  <rp>)</rp>
</ruby>う。
#+end_src

*** Implementation
{: .ordered}

To achieve a seamless, lightning-fast, and precise automatic Furigana injection
using the exact same technologies as Furiganator, we need to architect a
*Ruby-to-Node.js bridge*.

Spawning a new Node.js process for every single paragraph or file would be
extremely slow because Kuromoji's dictionaries take hundreds of milliseconds to
load. Instead, the solution uses a *persistent Node.js worker* that boots up
once per Jekyll build, loads the dictionary, and sits idly waiting for arrays of
text jobs over =stdin=.

Here is the complete implementation with the required comments and explanations.

**** Install Node.js Dependencies

Navigate to your plugin's directory and initialize the Node dependencies.
Kuroshiro and its analyzer are strictly required for the Node worker.

#+begin_src sh
cd lib/minimal_mistakes_plus
npm init -y
npm install kuroshiro kuroshiro-analyzer-kuromoji
#+end_src

**** The Node.js Worker (=kuroshiro_worker.js=)

Create a new file =lib/minimal_mistakes_plus/kuroshiro_worker.js=. This is the
high-performance daemon that parses Japanese morphology via Kuromoji and
converts it to HTML Ruby text.

**** The Updated Ruby File (=furigana.rb=)

Overwrite your existing =lib/minimal_mistakes_plus/furigana.rb=.

This code acts as the director. It handles global/local settings, strips out
manual syntax when toggled off, acts as an isolation barrier for
=<code>=/=<pre>= tags so Kuroshiro doesn't parse code blocks, and securely
streams strings back and forth with the Node worker.

**** GitHub Actions

You should commit the following files:

#+begin_example
kuroshiro_worker.js
package.json
package-lock.json
#+end_example

You must *not* commit the =node_modules= folder. It is already included in your
=.gitignore= file, which is the correct standard practice.

However, because you are not committing =node_modules=, there is a hidden trap
for GitHub Actions: when your workflow pulls your plugin as a Ruby Gem to build
the site, the Node.js dependencies will be missing, causing the Jekyll build to
crash when it tries to spawn the worker.

To solve this flawlessly without bloating your Git repository or requiring users
to modify their GitHub Actions YAML files, you can add a tiny "auto-install"
hook to your Ruby script. GitHub Actions (~ubuntu-latest~) has Node.js
pre-installed, so your plugin can simply instruct it to download the
dictionaries automatically on the very first run.

#+begin_src diff
--- lib/minimal_mistakes_plus/furigana.rb
+++ lib/minimal_mistakes_plus/furigana.rb
@@ -20,6 +20,12 @@
           @disabled = true
           return
         end
+
+        # Auto-install Node dependencies if missing (e.g., in GitHub Actions or fresh gem install)
+        unless Dir.exist?(File.join(File.dirname(__FILE__), 'node_modules'))
+          Jekyll.logger.info "Furigana:", "Installing Node.js dependencies. This may take a moment..."
+          system("npm install", chdir: File.dirname(__FILE__))
+        end
 
         @stdin, @stdout, @stderr, @wait_thr = Open3.popen3("node #{script_path}")
#+end_src
